<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Entree extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Entree_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('entree/entree_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Entree_model->json();
    }

    public function read($id) 
    {
        $row = $this->Entree_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'id_utilisateur' => $row->id_utilisateur,
		'nom' => $row->nom,
		'montant' => $row->montant,
		'date_entree' => $row->date_entree,
	    );
            $this->load->view('entree/entree_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('entree'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('entree/create_action'),
	    'id' => set_value('id'),
	    'id_utilisateur' => set_value('id_utilisateur'),
	    'nom' => set_value('nom'),
	    'montant' => set_value('montant'),
	    'date_entree' => set_value('date_entree'),
	);
        $this->load->view('entree/entree_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'id_utilisateur' => $this->input->post('id_utilisateur',TRUE),
		'nom' => $this->input->post('nom',TRUE),
		'montant' => $this->input->post('montant',TRUE),
		'date_entree' => $this->input->post('date_entree',TRUE),
	    );

            $this->Entree_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('entree'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Entree_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('entree/update_action'),
		'id' => set_value('id', $row->id),
		'id_utilisateur' => set_value('id_utilisateur', $row->id_utilisateur),
		'nom' => set_value('nom', $row->nom),
		'montant' => set_value('montant', $row->montant),
		'date_entree' => set_value('date_entree', $row->date_entree),
	    );
            $this->load->view('entree/entree_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('entree'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'id_utilisateur' => $this->input->post('id_utilisateur',TRUE),
		'nom' => $this->input->post('nom',TRUE),
		'montant' => $this->input->post('montant',TRUE),
		'date_entree' => $this->input->post('date_entree',TRUE),
	    );

            $this->Entree_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('entree'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Entree_model->get_by_id($id);

        if ($row) {
            $this->Entree_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('entree'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('entree'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('id_utilisateur', 'id utilisateur', 'trim|required');
	$this->form_validation->set_rules('nom', 'nom', 'trim|required');
	$this->form_validation->set_rules('montant', 'montant', 'trim|required|numeric');
	$this->form_validation->set_rules('date_entree', 'date entree', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Entree.php */
/* Location: ./application/controllers/Entree.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-02-08 23:05:23 */
/* http://harviacode.com */